name: Juice Shop CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -f Dockerfile -t juice-shop:latest .
          docker save juice-shop:latest > juice-shop.tar

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v3
        with:
          name: juice-shop-image
          path: juice-shop.tar

  image_scan:
    name: Build and Run Image Scan
    runs-on: ubuntu-latest
    needs: build_image
    steps:
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v3
        with:
          name: juice-shop-image

      - name: Load Docker Image
        run: docker load < juice-shop.tar

      - name: Docker Scout Scan
        uses: docker/scout-action@v1.15.1
        with:
          dockerhub-user: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          command: quickview,cves
          only-severities: critical,high
          sarif-file: scout-report.sarif
          exit-code: true

      - name: Upload Docker Scout Findings
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: docker-scout-findings
          path: scout-report.sarif

  dast_scan:
    name: Deploy and Run OWASP ZAP Scan
    runs-on: ubuntu-latest
    needs: build_image
    steps:
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v3
        with:
          name: juice-shop-image
  
      - name: Load Docker Image
        run: docker load < juice-shop.tar
  
      - name: Run Juice Shop Container
        run: |
          docker run -d -p 3000:3000 --name juice-shop juice-shop:latest
  
      - name: Pull OWASP ZAP Image
        run: docker pull owasp/zap2docker-stable
  
      - name: Run OWASP ZAP Container
        run: |
          docker run -t owasp/zap2docker-stable zap-full-scan.py \
            -t http://host.docker.internal:3000 \
            -r zap_report.html \
            --sarif > zap_report.sarif
  
      - name: Upload ZAP Scan Reports
        uses: actions/upload-artifact@v3
        with:
          name: zap-reports
          path: |
            zap_report.html
            zap_report.sarif
  
      - name: Stop Docker Containers
        if: always()
        run: |
          docker stop juice-shop && docker rm juice-shop
