name: Juice Shop CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  sast_scan:
    name: Static Analysis with Bandit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        run: bandit -r . -o bandit_report.txt -f txt

      - name: Upload Bandit Scan Report
        uses: actions/upload-artifact@v3
        with:
          name: bandit-report
          path: bandit_report.txt

  image_scan:
    name: Build and Scan Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t juice-shop:latest .

      - name: Perform Docker Scout Scan
        run: |
          docker scout quickview juice-shop:latest > docker_scout_report.txt

      - name: Upload Docker Scout Report
        uses: actions/upload-artifact@v3
        with:
          name: docker-scout-report
          path: docker_scout_report.txt

  dast_scan:
    name: Deploy and Run OWASP ZAP Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t juice-shop:latest .

      - name: Run Docker Container
        run: |
          docker run -d -p 3000:3000 --name juice-shop juice-shop:latest

      - name: Install OWASP ZAP CLI
        run: |
          sudo apt-get update && sudo apt-get install -y zaproxy

      - name: Run OWASP ZAP Scan
        run: |
          zap-cli quick-scan --self-contained --start-options="-config api.disablekey=true" http://localhost:3000 > zap_scan_report.txt

      - name: Upload OWASP ZAP Scan Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-scan-report
          path: zap_scan_report.txt

      - name: Stop Docker Container
        if: always()
        run: docker stop juice-shop
