name: Juice Shop CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -f Dockerfile -t juice-shop:latest .
          docker save juice-shop:latest > juice-shop.tar

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v3
        with:
          name: juice-shop-image
          path: juice-shop.tar

  sast_scan:
    name: Static Analysis with Snyk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Snyk
        run: npm install -g snyk

      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN

      - name: Run Snyk Code Scan
        run: |
          snyk code test --sarif  > snyk-results.sarif
        continue-on-error: true

      - name: Upload Snyk Findings
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: snyk-findings
          path: snyk-results.sarif
          

  image_scan:
    name: Build and Run Image Scan
    runs-on: ubuntu-latest
    needs: build_image
    steps:
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v3
        with:
          name: juice-shop-image

      - name: Load Docker Image
        run: docker load < juice-shop.tar

      - name: Docker Scout Scan
        uses: docker/scout-action@v1.15.1
        with:
          dockerhub-user: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          command: quickview,cves
          only-severities: critical,high
          sarif-file: scout-report.sarif
          exit-code: true

      - name: Upload Docker Scout Findings
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: docker-scout-findings
          path: scout-report.sarif

  dast_scan:
    name: ZAP Scan Baseline
    runs-on: ubuntu-latest
    needs: build_image
    continue-on-error: true
    steps:
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v3
        with:
          name: juice-shop-image
          
      - name: Load Docker Image
        run: docker load < juice-shop.tar

      - name: Run Juice Shop Container
        run: |
          docker run -d -p 3000:3000 --name juice-shop juice-shop:latest
        
      # Docs: https://github.com/zaproxy/action-baseline
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: "http://localhost:3000"
          cmd_options: "-a"
          allow_issue_writing: false
          artifact_name: "zap_scan"

      - name: Stop Docker Containers
        if: always()
        run: |
          docker stop juice-shop && docker rm juice-shop
